# mi_tuple = (1,2,(10,20),4)
# mi_tuple = list(mi_tuple)
# mi_tuple = tuple(mi_tuple)
# print(type(mi_tuple))
# print(mi_tuple[2])

mi_tuple = (1,2,3,1)
print(len(mi_tuple))
print(mi_tuple.count(1))
print(mi_tuple.index(2))